version: "3.4"

services:
  proshop:
    image: proshop
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:3000
